import { Maybe } from "./maybe.ts";
export * from "./maybe.ts";
export * from "./result.ts";
export { default as compose } from "just-compose";
export declare function identity<T>(value: T): T;
export declare function constant<T>(value: T): () => T;
export declare function at(idx: number): <T>(data: T[]) => Maybe<T>;
export declare function at<T>(data: T[], idx: number): Maybe<T>;
type Predicate<T> = (value: T, idx: number, arr: T[]) => boolean;
export declare function find<T>(predicate: Predicate<T>): (data: T[]) => Maybe<T>;
export declare function find<T>(data: T[], predicate: Predicate<T>): Maybe<T>;
export declare function findIndex<T>(predicate: Predicate<T>): (data: T[]) => Maybe<number>;
export declare function findIndex<T>(data: T[], predicate: Predicate<T>): Maybe<number>;
